[package]
name = "shid"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.15.0"
slotmap = "1.0.7"
ahash = "0.8.11"
owo-colors = "4.1.0"
palette = "0.7.6"
lyneate = "0.2.1"
paste = "1.0.15"
